image: docker:latest

services:
  - docker:dind

stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t test .     

release-image:
  stage: release
  script:
    - docker tag test test
    - docker push test
  only:
    - master
