image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

build:
  stage: build
  script:
    - docker build -t test . 
    - docker login -u yves -p uzWU4uKQfS2cKNpRsJEx $CI_REGISTRY
    - docker push test
