image: docker:latest

services:
  - docker:dind

stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay

build:
  stage: build
  script:
    - docker build -t test .     

release-image:
  stage: release
  script:
    - docker tag test $MY_CI_REGISTRY/test
    - docker push $MY_CI_REGISTRY/test
  only:
    - master
