image: docker:latest

services:
  - docker:dind

stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  script:    
    - docker build -t $CI_REGISTRY/robotframework/ubuntu-robotframework-firefox-chrome .

release-image:
  stage: release
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    #- docker tag $CI_REGISTRY/robotframework/ubuntu-robotframework-firefox-chrome ubuntu-robotframework-firefox-chrome
    - docker tag CI_REGISTRY_IMAGE CI_REGISTRY_IMAGE:test    
    - docker push CI_REGISTRY_IMAGE:test
  only:
    - master
