image: docker:latest

services:
  - docker:dind

stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  script:
    - docker build -t test .     

release-image:
  stage: release
  script:
    - docker tag test $CI_REGISTRY/test
    - docker push $CI_REGISTRY/test
  only:
    - master
