image: docker:latest

services:
  - docker:dind

stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  script:    
    - docker build -t $CI_REGISTRY/robotframework/ubuntu-robotframework-firefox-chrome .

release-image:
  stage: release
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag $CI_REGISTRY/robotframework/ubuntu-robotframework-firefox-chrome ubuntu-robotframework-firefox-chrome
    - docker push $CI_REGISTRY/robotframework/ubuntu-robotframework-firefox-chrome
  only:
    - master
